In [19]:
import pandas as pd

import sys
import os

project_root = os.path.abspath("..")

if project_root not in sys.path:
    sys.path.append(project_root)

# Load dataset
df = pd.read_excel("../data/raw/routes_performance.xlsx")

# Create empty list to store processed routes
route_dataset = []

# Group by Route ID
grouped_routes = df.groupby("Route ID")

# Process each route
for route_id, route_df in grouped_routes:

    # -----------------------------
    # Planned Route
    # -----------------------------
    planned_route_df = route_df.sort_values("IndexP")

    planned_route = planned_route_df["Address ID"].tolist()

    # -----------------------------
    # Actual Route
    # -----------------------------
    actual_route_df = route_df.sort_values("IndexA")

    actual_route = actual_route_df["Address ID"].tolist()

    # -----------------------------
    # Store in dataset
    # -----------------------------

    driver_id = route_df["Driver ID"].iloc[0]

    country = route_df["Country"].iloc[0]

    week_id = route_df["Week ID"].iloc[0]

    day_of_week = route_df["Day of Week"].iloc[0]


    planned_total_distance = (
    route_df["DistanceP"].sum()
    )

    actual_total_distance = (
        route_df["DistanceA"].sum()
    )
    route_dataset.append({

    "Route ID": route_id,

    "Driver ID": driver_id,

    "Country": country,

    "Week ID": week_id,

    "Day of Week": day_of_week,

    "Planned Route": planned_route,

    "Actual Route": actual_route,

    "Planned Stop Count":
        len(planned_route),

    "Actual Stop Count":
        len(actual_route),

    "Planned Distance":
        planned_total_distance,

    "Actual Distance":
        actual_total_distance
})

# Convert to DataFrame
route_dataset_df = pd.DataFrame(route_dataset)

# Show first 5 rows
print(route_dataset_df.head())

# Optional: dataset shape
print("\nDataset Shape:")
print(route_dataset_df.shape)

print(df[df["Route ID"] == 0][["Stop ID", "Address ID", "IndexP", "IndexA"]])

print(route_dataset_df.iloc[0]["Planned Route"])
print(route_dataset_df.iloc[0]["Actual Route"])

from src.metrics.rqs import calculate_rqs
from src.metrics.eds import calculate_eds
from src.metrics.dds import calculate_dds


route_dataset_df["RQS"] = route_dataset_df.apply(
    lambda row: calculate_rqs(
        row["Planned Route"],
        row["Actual Route"]
    ),
    axis=1
)

route_dataset_df["EDS"] = route_dataset_df.apply(
    lambda row: calculate_eds(
        row["Planned Route"],
        row["Actual Route"]
    ),
    axis=1
)

from src.metrics.dds import calculate_dds

route_dataset_df["DDS"] = route_dataset_df.apply(
    lambda row: calculate_dds(
        row["Planned Distance"],
        row["Actual Distance"]
    ),
    axis=1
)

print(
    route_dataset_df[
        ["RQS", "EDS", "DDS"]
    ].describe()
)

print(route_dataset_df.head())


print(
    route_dataset_df.sort_values(
        "RQS"
    ).head(5)
)
print(
    route_dataset_df.sort_values(
        "EDS"
    ).head(5)
)

print(
    route_dataset_df.sort_values(
        "DDS"
    ).head(5)
)

print()

print(
    route_dataset_df.sort_values(
        "DDS",
        ascending=False
    ).head(5)
)


from src.preprocessing.label_generator import generate_label

route_dataset_df["Label"] = route_dataset_df.apply(
    lambda row: generate_label(
        row["RQS"],
        row["EDS"],
        row["DDS"]
    ),
    axis=1
)

print(route_dataset_df["Label"].value_counts())

# --------------------------------
# Save processed dataset
# --------------------------------

route_dataset_df.to_pickle(
    "../data/processed/route_dataset.pkl"
)

route_dataset_df.to_csv(
    "../data/processed/route_dataset.csv",
    index=False
)

print("Dataset saved successfully!")

route_dataset_df.head()

   Route ID  Driver ID  Country  Week ID Day of Week  \
0         0          0        1        0      Monday
1         1          1        1        0      Monday
2         2          2        1        0      Monday
3         3          3        1        0      Monday
4         4          4        1        0      Monday

                             Planned Route  \
0                    [0, 1, 2, 3, 3, 0, 1]
1                    [0, 4, 5, 6, 7, 8, 9]
2              [0, 10, 11, 12, 13, 14, 15]
3  [0, 16, 17, 18, 19, 20, 21, 22, 20, 23]
4          [0, 24, 25, 26, 27, 28, 29, 30]

                              Actual Route  Planned Stop Count  \
0                    [0, 3, 3, 0, 1, 2, 1]                   7
1                    [0, 9, 4, 7, 6, 5, 8]                   7
2              [0, 12, 13, 11, 10, 14, 15]                   7
3  [0, 16, 19, 17, 18, 20, 22, 20, 21, 23]                  10
4          [0, 24, 30, 26, 27, 28, 29, 25]                   8

   Actual Stop Count  Planned Distance  Actual Distance
0                  7         49.468094        44.965197
1                  7         33.274342        33.610418
2                  7         12.124804        12.508786
3                 10         19.039848        19.374644
4                  8         20.632674        19.528799

Dataset Shape:
(19647, 11)
   Stop ID  Address ID  IndexP  IndexA
0        0           0       0       0
1        1           1       1       4
2        2           2       2       5
3        3           3       3       2
4        4           3       4       1
5        0           0       5       3
6        1           1       6       6
[0, 1, 2, 3, 3, 0, 1]
[0, 3, 3, 0, 1, 2, 1]
                RQS           EDS           DDS
count  19647.000000  19647.000000  19647.000000
mean       0.821134      0.325455     -0.001234
std        0.189716      0.261859      0.190915
min        0.000000      0.000000     -0.858500
25%        0.714300      0.000000     -0.027500
50%        0.875000      0.333300      0.000000
75%        1.000000      0.538500      0.016200
max        1.000000      1.000000      5.227400
   Route ID  Driver ID  Country  Week ID Day of Week  \
0         0          0        1        0      Monday
1         1          1        1        0      Monday
2         2          2        1        0      Monday
3         3          3        1        0      Monday
4         4          4        1        0      Monday

                             Planned Route  \
0                    [0, 1, 2, 3, 3, 0, 1]
1                    [0, 4, 5, 6, 7, 8, 9]
2              [0, 10, 11, 12, 13, 14, 15]
3  [0, 16, 17, 18, 19, 20, 21, 22, 20, 23]
4          [0, 24, 25, 26, 27, 28, 29, 30]

                              Actual Route  Planned Stop Count  \
0                    [0, 3, 3, 0, 1, 2, 1]                   7
1                    [0, 9, 4, 7, 6, 5, 8]                   7
2              [0, 12, 13, 11, 10, 14, 15]                   7
3  [0, 16, 19, 17, 18, 20, 22, 20, 21, 23]                  10
4          [0, 24, 30, 26, 27, 28, 29, 25]                   8

   Actual Stop Count  Planned Distance  Actual Distance     RQS     EDS  \
0                  7         49.468094        44.965197  0.5000  0.5714
1                  7         33.274342        33.610418  0.5000  0.5714
2                  7         12.124804        12.508786  0.6667  0.5714
3                 10         19.039848        19.374644  0.8400  0.4000
4                  8         20.632674        19.528799  0.6875  0.2500

      DDS
0 -0.0910
1  0.0101
2  0.0317
3  0.0176
4 -0.0535
       Route ID  Driver ID  Country  Week ID Day of Week  \
8780       8780        138        0       15     Tuesday
9481       9481        189        0       16     Tuesday
5916       5916        188        1       10    Thursday
14988     14988        229        0       24     Tuesday
17127     17127        396        0       27   Wednesday

                                           Planned Route  \
8780                       [904, 8271, 8272, 2364, 2432]
9481                                   [3341, 856, 6674]
5916                            [3169, 3179, 3342, 6747]
14988                      [868, 5543, 4429, 2364, 2594]
17127  [329, 10544, 3201, 9115, 6922, 5146, 3886, 105...

                                            Actual Route  Planned Stop Count  \
8780                       [2364, 2432, 904, 8271, 8272]                   5
9481                                   [856, 6674, 3341]                   3
5916                            [3342, 6747, 3169, 3179]                   4
14988                      [2364, 2594, 868, 5543, 4429]                   5
17127  [928, 4739, 4661, 3125, 7091, 329, 329, 10544,...                  16

       Actual Stop Count  Planned Distance  Actual Distance     RQS     EDS  \
8780                   5         84.462974        45.333481  0.0000  0.8000
9481                   3         96.818871        54.293354  0.0000  0.6667
5916                   4         34.699799        17.723316  0.0000  1.0000
14988                  5        202.427610       133.254303  0.0000  0.8000
17127                 16        321.730942       312.062125  0.0781  0.9375

          DDS
8780  -0.4633
9481  -0.4392
5916  -0.4892
14988 -0.3417
17127 -0.0301
       Route ID  Driver ID  Country  Week ID Day of Week  \
7431       7431        104        1       13   Wednesday
18360     18360         40        0       29    Thursday
18361     18361        381        1       29    Thursday
7497       7497        312        1       13   Wednesday
7496       7496        228        0       13   Wednesday

                                           Planned Route  \
7431   [3342, 1191, 4469, 3150, 303, 1195, 2447, 1193...
18360  [286, 1751, 7193, 7194, 6927, 7195, 7197, 1761...
18361  [3342, 439, 5895, 478, 454, 455, 2540, 3922, 1...
7497                                  [3342, 5891, 1539]
7496   [329, 329, 5866, 7874, 7875, 2200, 1791, 6027,...

                                            Actual Route  Planned Stop Count  \
7431   [3342, 1191, 4469, 3150, 303, 1195, 2447, 1193...                  10
18360  [286, 1751, 7193, 7194, 6927, 7195, 7197, 1761...                  13
18361  [3342, 439, 5895, 478, 454, 455, 2540, 3922, 1...                   9
7497                                  [3342, 5891, 1539]                   3
7496   [329, 329, 5866, 7874, 7875, 2200, 1791, 6027,...                   9

       Actual Stop Count  Planned Distance  Actual Distance  RQS  EDS  DDS
7431                  10         30.281434        30.281434  1.0  0.0  0.0
18360                 13         45.378244        45.378244  1.0  0.0  0.0
18361                  9         45.477319        45.477319  1.0  0.0  0.0
7497                   3         87.637666        87.637666  1.0  0.0  0.0
7496                   9         25.228281        25.228281  1.0  0.0  0.0
       Route ID  Driver ID  Country  Week ID Day of Week  \
4065       4065         12        1        7   Wednesday
18535     18535        125        1       29      Sunday
12882     12882        353        1       21   Wednesday
5352       5352        171        0        9      Friday
7232       7232        220        1       13      Monday

                                           Planned Route  \
4065   [3342, 33, 3342, 5484, 2055, 3342, 31, 35, 334...
18535  [3342, 5818, 8950, 3342, 2542, 3342, 1184, 334...
12882  [3342, 1, 935, 3342, 3, 3342, 4926, 3342, 5483...
5352   [286, 4234, 286, 5648, 2115, 286, 2887, 4170, ...
7232   [3342, 939, 3342, 590, 3342, 3544, 3342, 589, ...

                                            Actual Route  Planned Stop Count  \
4065   [3342, 3342, 3342, 3342, 3342, 3342, 5549, 554...                  17
18535  [3342, 3342, 3342, 3342, 3342, 3342, 3342, 554...                  16
12882  [3342, 3342, 3342, 3342, 3342, 3, 935, 5483, 3...                  12
5352   [286, 286, 286, 286, 4234, 5648, 2115, 2887, 4...                  11
7232   [3342, 3342, 3342, 3342, 3544, 589, 28, 939, 5...                  10

       Actual Stop Count  Planned Distance  Actual Distance     RQS     EDS  \
4065                  17        183.059720        25.909892  0.4306  0.7059
18535                 16        179.427880        27.940176  0.4062  0.6875
12882                 12        144.806501        22.700092  0.4722  0.6667
5352                  11        123.464888        21.235828  0.6667  0.4545
7232                  10        122.464716        24.218950  0.5200  0.7000

          DDS
4065  -0.8585
18535 -0.8443
12882 -0.8432
5352  -0.8280
7232  -0.8022

       Route ID  Driver ID  Country  Week ID Day of Week  \
5266       5266        219        0        9    Thursday
5066       5066        219        0        9     Tuesday
18933     18933        208        0       30   Wednesday
9483       9483        208        0       16     Tuesday
12423     12423        204        0       20      Friday

                                           Planned Route  \
5266   [565, 565, 565, 565, 565, 2135, 3623, 360, 198...
5066   [565, 565, 565, 565, 565, 4443, 1994, 2890, 28...
18933  [856, 856, 856, 856, 856, 856, 10771, 4152, 41...
9483                   [856, 856, 856, 8496, 4152, 4152]
12423  [329, 329, 329, 329, 1926, 4251, 928, 915, 915...

                                            Actual Route  Planned Stop Count  \
5266   [565, 2135, 565, 3623, 360, 1982, 565, 1984, 3...                  17
5066   [565, 4443, 1994, 565, 2890, 2821, 565, 4564, ...                  14
18933  [856, 4152, 856, 10771, 856, 10771, 856, 4152,...                  13
9483                   [856, 8496, 856, 4152, 856, 4152]                   6
12423  [1926, 329, 4251, 329, 928, 915, 1405, 329, 14...                  18

       Actual Stop Count  Planned Distance  Actual Distance     RQS     EDS  \
5266                  17         13.183798        82.101296  0.7222  0.4118
5066                  14         15.440989        73.535526  0.6122  0.5714
18933                 13        511.122760      2409.824486  0.5714  0.6154
9483                   6        206.990890       946.097224  0.6667  0.5000
12423                 18         28.627780       130.363236  0.6049  0.6667

          DDS
5266   5.2274
5066   3.7624
18933  3.7148
9483   3.5707
12423  3.5537
Label
D     12158
ND     7489
Name: count, dtype: int64
Dataset saved successfully!

,Route ID,Driver ID,Country,Week ID,Day of Week,Planned Route,Actual Route,Planned Stop Count,Actual Stop Count,Planned Distance,Actual Distance,RQS,EDS,DDS,Label
0,0,0,1,0,Monday,"[0, 1, 2, 3, 3, 0, 1]","[0, 3, 3, 0, 1, 2, 1]",7,7,49.468094,44.965197,0.5000,0.5714,-0.0910,D
1,1,1,1,0,Monday,"[0, 4, 5, 6, 7, 8, 9]","[0, 9, 4, 7, 6, 5, 8]",7,7,33.274342,33.610418,0.5000,0.5714,0.0101,D
2,2,2,1,0,Monday,"[0, 10, 11, 12, 13, 14, 15]","[0, 12, 13, 11, 10, 14, 15]",7,7,12.124804,12.508786,0.6667,0.5714,0.0317,D
3,3,3,1,0,Monday,"[0, 16, 17, 18, 19, 20, 21, 22, 20, 23]","[0, 16, 19, 17, 18, 20, 22, 20, 21, 23]",10,10,19.039848,19.374644,0.8400,0.4000,0.0176,D
4,4,4,1,0,Monday,"[0, 24, 25, 26, 27, 28, 29, 30]","[0, 24, 30, 26, 27, 28, 29, 25]",8,8,20.632674,19.528799,0.6875,0.2500,-0.0535,D

In [3]:
from src.metrics.eds import calculate_eds

route_dataset_df["EDS"] = route_dataset_df.apply(
    lambda row: calculate_eds(
        row["Planned Route"],
        row["Actual Route"]
    ),
    axis=1
)

print(route_dataset_df[["RQS", "EDS"]].describe())

                RQS           EDS
count  19647.000000  19647.000000
mean       0.821134      0.325455
std        0.189716      0.261859
min        0.000000      0.000000
25%        0.714300      0.000000
50%        0.875000      0.333300
75%        1.000000      0.538500
max        1.000000      1.000000

In [11]:
from src.preprocessing.label_generator import generate_label

route_dataset_df["Label"] = route_dataset_df.apply(
    lambda row:
        generate_label(
            row["RQS"],
            row["EDS"],
            row["DDS"]
        ),
    axis=1
)

print(
    route_dataset_df["Label"]
    .value_counts()
)

Label
D     12158
ND     7489
Name: count, dtype: int64

In [13]:
route_dataset_df["Label"] = (
    (route_dataset_df["RQS"] >= 0.85) &
    (route_dataset_df["EDS"] <= 0.30) &
    (route_dataset_df["DDS"] <= 0.03)
)

route_dataset_df["Label"] = route_dataset_df["Label"].map(
    {
        True: "ND",
        False: "D"
    }
)

print(route_dataset_df["Label"].value_counts())

print(
    "\nPercentage:\n",
    round(
        route_dataset_df["Label"]
        .value_counts(normalize=True) * 100,
        2
    )
)

print(
    route_dataset_df[
        [
            "RQS",
            "EDS",
            "DDS",
            "Label"
        ]
    ].head(10)
)

Label
D     11505
ND     8142
Name: count, dtype: int64

Percentage:
 Label
D     58.56
ND    41.44
Name: proportion, dtype: float64
      RQS     EDS     DDS Label
0  0.5000  0.5714 -0.0910     D
1  0.5000  0.5714  0.0101     D
2  0.6667  0.5714  0.0317     D
3  0.8400  0.4000  0.0176     D
4  0.6875  0.2500 -0.0535     D
5  0.2000  0.8000 -0.1820     D
6  0.6735  0.5714 -0.0097     D
7  0.6964  0.7333  0.1843     D
8  0.9167  0.2857 -0.0353    ND
9  0.2000  0.7273 -0.2616     D

In [15]:
from src.preprocessing.label_generator import generate_label

route_dataset_df["Label"] = route_dataset_df.apply(
    lambda row: generate_label(
        row["RQS"],
        row["EDS"],
        row["DDS"]
    ),
    axis=1
)

print(route_dataset_df["Label"].value_counts())

print(
    round(
        route_dataset_df["Label"]
        .value_counts(normalize=True) * 100,
        2
    )
)

print(
    route_dataset_df[
        ["RQS", "EDS", "DDS", "Label"]
    ].head(10)
)

Label
D     12158
ND     7489
Name: count, dtype: int64
Label
D     61.88
ND    38.12
Name: proportion, dtype: float64
      RQS     EDS     DDS Label
0  0.5000  0.5714 -0.0910     D
1  0.5000  0.5714  0.0101     D
2  0.6667  0.5714  0.0317     D
3  0.8400  0.4000  0.0176     D
4  0.6875  0.2500 -0.0535     D
5  0.2000  0.8000 -0.1820     D
6  0.6735  0.5714 -0.0097     D
7  0.6964  0.7333  0.1843     D
8  0.9167  0.2857 -0.0353     D
9  0.2000  0.7273 -0.2616     D

In [16]:
route_dataset_df.head()

,Route ID,Planned Route,Actual Route,Planned Stop Count,Actual Stop Count,Planned Distance,Actual Distance,RQS,EDS,DDS,Label
0,0,"[0, 1, 2, 3, 3, 0, 1]","[0, 3, 3, 0, 1, 2, 1]",7,7,49.468094,44.965197,0.5000,0.5714,-0.0910,D
1,1,"[0, 4, 5, 6, 7, 8, 9]","[0, 9, 4, 7, 6, 5, 8]",7,7,33.274342,33.610418,0.5000,0.5714,0.0101,D
2,2,"[0, 10, 11, 12, 13, 14, 15]","[0, 12, 13, 11, 10, 14, 15]",7,7,12.124804,12.508786,0.6667,0.5714,0.0317,D
3,3,"[0, 16, 17, 18, 19, 20, 21, 22, 20, 23]","[0, 16, 19, 17, 18, 20, 22, 20, 21, 23]",10,10,19.039848,19.374644,0.8400,0.4000,0.0176,D
4,4,"[0, 24, 25, 26, 27, 28, 29, 30]","[0, 24, 30, 26, 27, 28, 29, 25]",8,8,20.632674,19.528799,0.6875,0.2500,-0.0535,D